### ISSUE TITLE
Source code or model

### ISSUE THREAD

**Issue by JohnMe** [dvlab-research/RIVAL#1]
Hi, thanks for your interesting paper. Are you still planning the source code and / or the pretrained model?

**Comment by JulianJuaner** [comment]
I appreciate your interest. As this work is currently under review, the code will be released after the result is released.
This work is a training-free method. We only use the pretrained SD model (e.g. SD-1-5).

**Comment by sanchit88** [comment]
Hi @JulianJuaner, can you please tell us roughly when the code will be released? Thanks!

**Comment by JulianJuaner** [comment]
> Hi @JulianJuaner, can you please tell us roughly when the code will be released? Thanks!

Thanks for your interest! We are planning to release the code in late July.

**Comment by Linfeng-Tang** [comment]
Very interesting work, looking forward to its source code!

**Comment by Njasa2k** [comment]
Has the code been delayed?

**Comment by JulianJuaner** [comment]
Dear all,

Thank you for your attention to this work. Since I wrongly estimated the paper's review timeline (qwq), the code release time will be slightly delayed. I hope you can understand. Thank you!

**Comment by yy9568** [comment]
@JulianJuaner Hi~How is the progress now?

**Comment by JulianJuaner** [comment]
> @JulianJuaner Hi~How is the progress now?

@zhouyuangan We are now preparing the code and paper for the NeurIPS camera-ready release **(deadline 27th Oct.)**. **We will release the full code before [2023.11.3]**  
Now, we are working on the code cleaning and reformatting. 
Thank you for your patience QoQ.

**Comment by junwuzhang19** [comment]
Hi! It's already 10.30 now, still no code has been released. I'd like to know how long it'll be extended, especially for the inference code of the example-based inpainting. Thanks!

**Comment by JulianJuaner** [comment]
> Hi! It's already 10.30 now, still no code has been released. I'd like to know how long it'll be extended, especially for the inference code of the example-based inpainting. Thanks!

Hi @junwuzhang19, sorry for the delay. As the edited comment said, the official code release will be on 11.3;
**The under-constructed code is placed in the dev branch (including examples of variation generation)**. I will keep updating this branch before the official release. 
As for example-based inpainting, I originally didn't plan to open-source it. I will try to open-source it by November 3rd. However, please note that its application scope is indeed limited (as shown in the paper, the example can only come from itself).

**Comment by junwuzhang19** [comment]
> > Hi! It's already 10.30 now, still no code has been released. I'd like to know how long it'll be extended, especially for the inference code of the example-based inpainting. Thanks!
> 
> Hi @junwuzhang19, sorry for the delay. As the edited comment said, the official code release will be on 11.3;
> **The under-constructed code is placed in the dev branch (including examples of variation generation)**. I will keep updating this branch before the official release. 
> As for example-based inpainting, I originally didn't plan to open-source it. I will try to open-source it by November 3rd. However, please note that its application scope is indeed limited (as shown in the paper, the example can only come from itself).

Thanks for your prompt reply and released under-constructed code!

**Comment by JulianJuaner** [comment]
Thank you all for your patience. We have released the v1 version of the code for RIVAL. Due to the haste in open sourcing, please don't hesitate to raise any issues.
