### ISSUE TITLE
One of the formulas in the paper seems to have an error

### ISSUE THREAD

**Issue by Arlo0321** [dvlab-research/RIVAL#2]
Thanks to the authors for such influential work.

Equation 5 seems to be incorrect, refer to the equation 7 in the paper "DiffusionCLIP: Text-Guided Diffusion Models for Robust Image Manipulation".
![image](https://github.com/JulianJuaner/RIVAL/assets/51200306/5083a539-690e-41ae-b680-b355a54cb75a)
![image](https://github.com/JulianJuaner/RIVAL/assets/51200306/03ff04a0-9a53-4a86-996b-5649954dec77)
These two equations do not seem to be equivalent. Could the author give the derivation of Equation 5.

**Comment by Arlo0321** [comment]
![image](https://github.com/JulianJuaner/RIVAL/assets/51200306/99b73b59-d79b-4d90-ace3-fdfee8ae9632)
Also, would you mind further explaining the marked passage, I'm a bit confused.

**Comment by JulianJuaner** [comment]
Hi, thank you for your detailed reading of this work. Regarding Equation 5 (DDIM sampling part), we refer to the representation of the null-text-inversion paper (https://arxiv.org/pdf/2211.09794.pdf)

<img width="344" alt="Screenshot 2023-07-02 at 9 37 39 PM" src="https://github.com/JulianJuaner/RIVAL/assets/37148692/21f854c9-b2d6-4ba1-9adb-ff7caa19d535">

compared with eq.(5) of RIVAL paper:

<img width="976" alt="Screenshot 2023-07-02 at 9 40 12 PM" src="https://github.com/JulianJuaner/RIVAL/assets/37148692/50e349bb-4a54-479f-8ea2-8e23600ac542">

We also add a similar explanation in Appendix(A).

For the marked contents, as the inversion process of DDIM is deterministic, it can predict a noise term in each step, then invert the previous-step latent using this noise term and the noisy latent. However, this process does not guarantee that the inverted latent should be formed in a standard Gaussian (N(0, I)). This causes the latents in the inversion chain to potentially have different distributions from the vanilla inverse diffusion process (e.g., generating images from a standard Gaussian). When we try to apply cross-image self-attention (Sec. 3.1), the distribution differences between the two chains (real-inversion & generation) create a distribution gap of KQV terms, which affects the attention calculation and leads to a diverse generation result (Fig. 3)

<img width="1001" alt="Screenshot 2023-07-02 at 9 50 07 PM" src="https://github.com/JulianJuaner/RIVAL/assets/37148692/78cb549d-9caa-4b7d-ae1a-151e5ddb94b7">

**Comment by Arlo0321** [comment]
Thank you very much for your reply, it is very useful for me. @JulianJuaner 

For the question of the formula, I have read this paper. It may be a typo and the original paper has been revised in its CVPR camera ready version. Reference can be made to this link: [https://github.com/google/prompt-to-prompt/issues/55](url)

“CVPR camera ready version had fixed this.
https://openaccess.thecvf.com/content/CVPR2023/papers/Mokady_NULL-Text_Inversion_for_Editing_Real_Images_Using_Guided_Diffusion_Models_CVPR_2023_paper.pdf“

For the second question, thank you for your patience to explain.

**Comment by JulianJuaner** [comment]
> https://openaccess.thecvf.com/content/CVPR2023/papers/Mokady_NULL-Text_Inversion_for_Editing_Real_Images_Using_Guided_Diffusion_Models_CVPR_2023_paper.pdf“

@houjie8888 
Thank you for your correction of the formula. We will check and revise our paper in the later version.
I will temporarily close this issue. If you have any further questions about this paper, please feel free to re-open this issue~

**Comment by Arlo0321** [comment]
hi @JulianJuaner 

I have some questions about adaptive normalization as I'm re-reading this paper today and would appreciate your response.

![image](https://github.com/JulianJuaner/RIVAL/assets/51200306/bcaa73ec-b00d-4d11-b362-b89d4210191c)

I would like to know if the noise predicted by DM needs to be normalized. As I understand adaptive normalization, here it may be necessary to first normalize the noise before multiplying by the mean and adding the variance. Is there any underlying theory for Eq. 9 in the paper, and what is it doing?

**Comment by houjie8888** [comment]
like this:
$$
\sigma \left( \varepsilon _{\theta}\left( X_{R}^{t} \right) \right) \left( \left( \varepsilon _{\theta}^{cfg}\left( X_{G}^{t} \right) -\mu \left( \varepsilon _{\theta}^{cfg}\left( X_{G}^{t} \right) \right) \right) /\sigma \left( \varepsilon _{\theta}^{cfg}\left( X_{G}^{t} \right) \right) \right) +\mu \left( \varepsilon _{\theta}^{cfg}\left( X_{G}^{t} \right) \right) 
$$

**Comment by Arlo0321** [comment]
like this:

![image](https://github.com/JulianJuaner/RIVAL/assets/51200306/612a1f06-02ac-4ccf-92bf-66fa64422786)

**Comment by JulianJuaner** [comment]
Thank you very much for your correction. We have urgently checked our implementation and paper, and indeed, you are right. Due to the rush when writing the paper, we did not conduct a thorough review and made this very basic mistake, for which we are deeply sorry. We will revise the parts mentioned in our published paper as soon as possible. Thanks again!

<img width="573" alt="Screenshot 2023-07-14 at 6 45 22 PM" src="https://github.com/JulianJuaner/RIVAL/assets/37148692/01484485-b64d-4e39-8f48-50af2e0f6ec8">


From StyleGAN paper:

<img width="247" alt="Screenshot 2023-07-14 at 6 59 06 PM" src="https://github.com/JulianJuaner/RIVAL/assets/37148692/cf29cf48-b60c-437c-863f-08b96eec189b">

Here is the code of the AdaIN implementation used in our work.
```python
def adain(feat, cond_feat, eps=1e-5):
    # eps is a small value added to the variance to avoid divide-by-zero.
    size = feat.size() # [d, c]
    C = size[1]
    feat_var = feat.var(dim=0) + eps
    feat_std = feat_var.sqrt().view(1, C)
    feat_mean = feat.mean(dim=0).view(1, C)
    
    cond_feat_var = cond_feat.var(dim=0) + eps
    cond_feat_std = cond_feat_var.sqrt().view(1, C)
    cond_feat_mean = cond_feat.mean(dim=0).view(1, C)
    feat = (feat - feat_mean.expand(size)) / feat_std.expand(size)
    return feat * cond_feat_std.expand(size) + cond_feat_mean.expand(size)
```

**Comment by Arlo0321** [comment]
Haha, I searched a lot of normalization methods for this. 

Very much anticipating future code releases, and still thank you for contributing to the community. (●'◡'●)
