### ISSUE TITLE
Bug in the denoising loop (?)

### ISSUE THREAD

**Issue by johnMinelli** [dvlab-research/RIVAL#8]
Hi, thank you for sharing your work. I was wondering if this is correct:
https://github.com/dvlab-research/RIVAL/blob/4932d49c19b9673e1cde74f6ee69e967239bc466/rival/sd_pipeline_controlnet.py#L174

`chain` is a list of 51, `i` is 0 at the first iterations but the last element in the inversion chain has already been used so maybe there is a misalligment? i.e. -2 instead of -1

**Comment by JulianJuaner** [comment]
Thank you for raising this issue. You are right, the current version has a 1-step misalignment between two latents. We will fix it ASAP.
